/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 walk.gltf --transform 
Files: walk.gltf [396.87KB] > C:\Users\AsH23\OneDrive\Desktop\walk\walk-transformed.glb [86.65KB] (78%)
Author: Denys Almaral (https://sketchfab.com/denysalmaral)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-humanoid-robot-bad584b9fbe04c85bc57438842969270
Title: Low Poly Humanoid Robot
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Walk(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/walk-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.lpRobot}
          skeleton={nodes.Object_7.skeleton}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/walk-transformed.glb");
